### PR TITLE
Useunlsh

### PR DESCRIPTION
**Pull request by krolchonok**
# What's new

Again, again and again!

Не используйте эту "прошивку". Unleashed лучше!

Do not use this "firmware". Unleashed is better!

https://github.com/DarkFlippers/unleashed-firmware

### CODE REVIEW

**Comment by ankris812** [comment]
what? what do you achieve with this?

**Comment by krolchonok** [comment]
> what? what do you achieve with this?

improving the level of ecology in the world

**Comment by ankris812** [comment]
> > what? what do you achieve with this?
> 
> improving the level of ecology in the world

what??

**Comment by krolchonok** [comment]
> > > what? what do you achieve with this?
> > 
> > improving the level of ecology in the world
> 
> what??
> 

the level of ecology in the world is falling, widespread pollution

**Comment by ankris812** [comment]
> > > > what? what do you achieve with this?
> > > 
> > > 
> > > improving the level of ecology in the world
> > 
> > 
> > what??
> 
> the level of ecology in the world is falling, widespread pollution

and using another firm will change that? please dont use drugs when writing something on internet

**Comment by krolchonok** [comment]
soooo bored

**Comment by ankris812** [comment]
> soooo bored

i see, i'll block you

**Pull request closed without merging**
